ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views

app_name="cart"

urlpatterns = [
    path('addcart/<int:p>',views.addtocart,name="addcart"),
    path('cartview',views.cart_view,name="cartview"),
    path('remove/<int:p>',views.cart_decrement,name="cart_remove"),
    path('delete/<int:p>',views.delete_cart,name="delete_cart"),
    path('orderform', views.orderform, name="orderform"),
    path('orderview', views.orderview, name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views

app_name="search"


urlpatterns = [
    path('search/', views.Searchpro, name="searchpro"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name='allcat'),
    path('allproducts/<int:pk>',views.allproducts,name="allproducts"),
    path('prodetail/<int:p>',views.showdetail,name='prodetail'),
    path('regis/',views.register,name="regis"),
    path('login/',views.U_login,name="login"),
    path('logout/',views.U_logout,name="logout"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.

class cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    data_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_items=models.IntegerField()
    phone=models.BigIntegerField()
    address=models.TextField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    ordered_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

    def __str__(self):
        return self.user.username




class Account(models.Model):
    acc_no=models.BigIntegerField()
    acc_type=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acc_no)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from shop.models import Product
from cart.models import cart,Account,Order

# Create your views here.

@login_required
# for displaying the cart for current user
def cart_view(request):
    u=request.user
    c=cart.objects.filter(user=u)
    total=0
    for i in c:
        total=total+i.quantity*i.product.price
    return render(request,'cart.html',{'c':c,'total':total})

@login_required
# for adding particular product to cart table
def addtocart(request,p):
    p=Product.objects.get(id=p)
    u=request.user
    try:
        Cart=cart.objects.get(user=u,product=p)
        if p.stock>0:
            Cart.quantity += 1
            Cart.save()
            p.stock -=1
            p.save()

    except:
        if p.stock>0:
            Cart = cart.objects.create(product=p, user=u, quantity=1)
            Cart.save()
            p.stock -=1
            p.save

    return cart_view(request)


def cart_decrement(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        Cart = cart.objects.get(user=u, product=p)
        if(Cart.quantity>1):

            Cart.quantity -=1
            Cart.save()
            p.stock +=1
            p.save()
        else:
            Cart.delete()
            p.stock +=1
            p.save()

    except:
        pass
    return cart_view(request)

def delete_cart(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        Cart = cart.objects.get(user=u, product=p)
        Cart.delete()
        p.stock += cart.quantity
        p.save()

    except:
        pass
    return cart_view(request)

def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']



        u=request.user
        c=cart.objects.filter(user=u)

        total=0
        for i in c:
            total=total+i.quantity*i.product.price


        try:
            ac=Account.objects.get(acc_no=n)
            if(ac.amount >= total):

                ac.amount=ac.amount-total

                ac.save()
                for i in c:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_items=i.quantity,ordered_status="paid")
                    o.save()

                c.delete()
                msg="Order Placed Sucessfully"
                print(msg)
                return render(request,'orderdetail.html',{'message':msg})

            else:

                msg="Sorry,Insufficient balance"
                return render(request, 'orderdetail.html', {'message': msg})


        except:
            pass


    return render(request,'orderform.html')

@login_required
def orderview(request):

    u=request.user
    o = Order.objects.filter(user=u)

    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


# Create your views here.
def Searchpro(request):
    p=None
    query=""
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            p=Product.objects.filter(Q(name__icontains=query))
    return render(request,'search.html',{'p':p,'q':query})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat&family=Caveat+Brush&family=Encode+Sans+Semi+Expanded:wght@100;200;300;400;500;600;700;800;900&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet">

    <script src="{% static 'js/script.js' %}"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'shop:allcat' %}">
                <img src="{% static 'images/logoecom4.jpg' %}" style="height:50px; width:50px;"/>
            </a>
            <a class="navbar-brand" href="{% url 'shop:allcat' %}">MyShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            All Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for i in link %}
                            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.id %}">{{i.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>

                    {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
                    </li>

                    {% if user.is_superuser != True %}

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup style="color:black;font-size:18px;">{{count}}</sup></a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
                    </li>

                    {% endif %}


                    {% else %}

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shop:regis' %}">Signup</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
                    </li>

                    {% endif %}



                </ul>
                <form class="d-flex" method="POST" action="{% url 'search:searchpro' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                    <button class="btn btn-outline-danger ms-2 pe-4 search-button" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<div class="mt-2" style="padding-top: 80px;"> <!-- Adding padding to push content below the navbar -->
    {% block content %}
    {% endblock %}
</div>

<footer id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <hr>
                <center>
                    <p><i class="fa-regular fa-copyright"></i> 2024 | Shopy.com</p>
                </center>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid"> <!-- Adding padding to push content down below the navbar -->
    <div class="row">
        <div class="col-12">
            <h4 class="text-center text-dark">Shopping Cart</h4>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-7">
            <table class="table table-bordered">
                <tr>
                    <th colspan="6">Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td>{{i.product.name}}</td>
                    <td><b>Product ID:{{i.product.id}}</b><br>
                    <b>Quantity:{{i.quantity}}</b><br>
                    <b>Unit Price:{{i.quantity}}*{{i.product.price}}</b></td>
                    <td>Subtotal:{{i.subtotal}}</td>


                    <td>
                         {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addcart' i.product.id %}"><i class="fa-solid fa-square-plus" style="color:green"></i></a>
                        <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-regular fa-square-minus"style="color:red"></i></a>
                        <a href="{% url 'cart:delete_cart' i.product.id %}"><i class="fa-solid fa-trash" style="color:black"></i></a> </td>
                         {% else %}
                       <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-regular fa-square-minus"style="color:red"></i></a>
                       <a href="{% url 'cart:delete_cart' i.product.id %}"><i class="fa-solid fa-trash" style="color:black"></i></a>
                         {% endif %}
                    </td>

                </tr>
                {% endfor %}
            </table>
        </div>

        <div class="col-4">
            <table class="table table-bordered" style="position:relative;">
                <tr>
                    <th colspan="">Checkout</th>
                </tr>
                <tr>
                    <td colspan="4">Total Amount:{{total}}</td>
                </tr>
            </table>
            <a class="btn btn-danger me-5" href="{% url 'cart:orderform' %}">Place Order</a>
            <a class="btn btn-danger" href="{% url 'shop:allcat' %}" style="position:absolute;right0;">Continue Shopping</a>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4 me-5 pt-3 pb-4" style="padding-left:100px;">
            <img class="mt-5" src="{{ pro.image.url }}"height="320px" width="300px">
        </div>
        <div class="col-6 me-5 mt-5 pt-3" style="padding-left:100px; width:750px;">
            <h1>{{pro.name}}</h1>
            <h5 mt-2>${{pro.price}}</h5>
            <p class="mt-2">{{pro.description}}</p>
            <h5 class="mt-2">Currently available:{{pro.stock}}</h5>
            {% if user.is_superuser == True %}
            {% if pro.stock > 0 %}

            <h3 class="text-success">Product in Stock</h3>
            <a href="{% url 'admin:index' %}" class="btn btn-outline-danger mt-4">Add Stock</a>
            {% else %}

            <h3 class="text-success">Product Out of Stock</h3>
            <a href="{% url 'admin:index'  %}" class="btn btn-outline-danger mt-4">Add Stock</a>
            {% endif %}

            {% else %}
            {% if pro.stock > 0 %}
            <a href="{% url 'cart:addcart' pro.id %}" class="btn btn-outline-danger mt-4">Add to Cart</a>
            {% else %}
            <h3 class="text-danger">Out of Stock</h3>
            {% endif %}


            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>

    button {
  position: relative;
  margin: 0;
  padding: 0.8em 1em;
  outline: none;
  text-decoration: none;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: none;
  text-transform: uppercase;
  background-color: #333;
  border-radius: 10px;
  color: #fff;
  font-weight: 300;
  font-size: 18px;
  font-family: inherit;
  z-index: 0;
  overflow: hidden;
  transition: all 0.3s cubic-bezier(0.02, 0.01, 0.47, 1);
  margin-top:5px;
}

button:hover {
  animation: sh0 0.5s ease-in-out both;
}

@keyframes sh0 {
  0% {
    transform: rotate(0deg) translate3d(0, 0, 0);
  }

  25% {
    transform: rotate(7deg) translate3d(0, 0, 0);
  }

  50% {
    transform: rotate(-7deg) translate3d(0, 0, 0);
  }

  75% {
    transform: rotate(1deg) translate3d(0, 0, 0);
  }

  100% {
    transform: rotate(0deg) translate3d(0, 0, 0);
  }
}

button:hover span {
  animation: storm 0.7s ease-in-out both;
  animation-delay: 0.06s;
}

button::before,
button::after {
  content: '';
  position: absolute;
  right: 0;
  bottom: 0;
  width: 100px;
  height: 100px;
  border-radius: 50%;
  background: #fff;
  opacity: 0;
  transition: transform 0.15s cubic-bezier(0.02, 0.01, 0.47, 1), opacity 0.15s cubic-bezier(0.02, 0.01, 0.47, 1);
  z-index: -1;
  transform: translate(100%, -25%) translate3d(0, 0, 0);
}

button:hover::before,
button:hover::after {
  opacity: 0.15;
  transition: transform 0.2s cubic-bezier(0.02, 0.01, 0.47, 1), opacity 0.2s cubic-bezier(0.02, 0.01, 0.47, 1);
}

button:hover::before {
  transform: translate3d(50%, 0, 0) scale(0.9);
}

button:hover::after {
  transform: translate(50%, 0) scale(1.1);
}




  </style>
</head>
<body>

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100" style="height:200px;">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;" >
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="POST">
                  {% csrf_token %}


                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Logo</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                  <div class="form-outline mb-4">
                    <input type="text" id="form2Example17" class="form-control form-control-lg" name="u" />
                    <label class="form-label" for="form2Example17">Username</label>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="password" id="form2Example27" class="form-control form-control-lg" name="p" />
                    <label class="form-label" for="form2Example27">Password</label>
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                    <a href="{% url 'shop:allcat' %}" class="btn btn-dark btn-lg btn-block">Back</a>
                  </div>



                  <a class="small text-muted" href="#!">Forgot password?</a>
                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'shop:regis' %}"
                      style="color: #393f81;">Register here</a></p>
                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <h4 class="text-center text-success">{{message}}</h4>
    <h6 class="text-center">Thank you....</h6>
    <h5 class="text-center text-light"><a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue</a></h5>
</div>

{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container d-flex justify-content-center align-items-center">
    <div class="card">
        <div class="card-body">
            <h1 class="text-center mb-4">Details</h1>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" name="a" id="address" placeholder="Enter Address">
                </div>
                <div class="form-group">
                    <label for="phone">Phone No.</label>
                    <input type="number" class="form-control" name="p" id="phone" placeholder="Enter Phone No.">
                </div>

                <div class="form-group">
                    <label for="accno">Account No.</label>
                    <input type="number" class="form-control" name="n" id="accno" placeholder="Enter Account No.">
                </div>


                <button type="submit" class="but">Submit</button>
            </form>
        </div>
    </div>
</div>

<style>
    .card {
        width: 600px;
    }

    .container {
        padding: 20px;
        border: 1px solid violet;
        border-radius: 5px;
        box-shadow: 0 0 10px blue;
        background-color: currentColor;
    }

    label {
        font-weight: bold;
    }


    input[type="text"],
    input[type="password"],
    input[type="email"] {
        width: 100%;
        padding: 10px;
        border: 1px solid violet;
        border-radius: 5px;
        box-sizing: border-box;
    }



element.style {

    margin-top: 40px;
}



button {
  position: relative;
  margin: 0;
  padding: 0.8em 1em;
  outline: none;
  text-decoration: none;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: none;
  text-transform: uppercase;
  background-color: #333;
  border-radius: 10px;
  color: #fff;
  font-weight: 300;
  font-size: 18px;
  font-family: inherit;
  z-index: 0;
  overflow: hidden;
  transition: all 0.3s cubic-bezier(0.02, 0.01, 0.47, 1);
  margin-top:5px;
}

button:hover {
  animation: sh0 0.5s ease-in-out both;
}

@keyframes sh0 {
  0% {
    transform: rotate(0deg) translate3d(0, 0, 0);
  }

  25% {
    transform: rotate(7deg) translate3d(0, 0, 0);
  }

  50% {
    transform: rotate(-7deg) translate3d(0, 0, 0);
  }

  75% {
    transform: rotate(1deg) translate3d(0, 0, 0);
  }

  100% {
    transform: rotate(0deg) translate3d(0, 0, 0);
  }
}

button:hover span {
  animation: storm 0.7s ease-in-out both;
  animation-delay: 0.06s;
}

button::before,
button::after {
  content: '';
  position: absolute;
  right: 0;
  bottom: 0;
  width: 100px;
  height: 100px;
  border-radius: 50%;
  background: #fff;
  opacity: 0;
  transition: transform 0.15s cubic-bezier(0.02, 0.01, 0.47, 1), opacity 0.15s cubic-bezier(0.02, 0.01, 0.47, 1);
  z-index: -1;
  transform: translate(100%, -25%) translate3d(0, 0, 0);
}

button:hover::before,
button:hover::after {
  opacity: 0.15;
  transition: transform 0.2s cubic-bezier(0.02, 0.01, 0.47, 1), opacity 0.2s cubic-bezier(0.02, 0.01, 0.47, 1);
}

button:hover::before {
  transform: translate3d(50%, 0, 0) scale(0.9);
}

button:hover::after {
  transform: translate(50%, 0) scale(1.1);
}





</style>

{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container mt-5">
    <h5 class="text-center">Name of the Customer:{{u}}</h5>
     {% for i in o %}
     <div class="row">

        <div class="col-4 mt-3 ms-5 me-5"><img src="{{i.product.image.url}}"height="150px" width="150px"></div>
         <div class="col-4 mt-3">
             <h6>Product Name:{{i.product.name}}</h6>
             <h6>Price:{{i.product.price}}</h6>
             <h6>Quantity:{{i.product.no_items}}</h6>
             <h6>Address:{{i.address}}</h6>
             <h6>Phone:{{i.phone}}</h6>
             <h6 class="text text-dark">Ordered On:{{i.ordered_date}}</h6>
             <h6 class="text text-dark">Delivery Status:{{i.delivery_status}}</h6>

         </div>
        </div>
    {% endfor %}
    </div>


{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="pro" style="margin-bottom:30px;">
    <img src="{{c.image.url}}" height="650px" width="100%">
</div>

<div class="container-fluid mt-1" style="margin-bottom:100px">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2">{{c.desc}}</p>
</div>

<div class="container" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
            <img src="{{ i.image.url }}" width="100%" height="200px" class="card-img-top" alt="...">
                 <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                     <p class="card-text" style="text-align:justify;"></p>
                     <a href="{% url 'shop:prodetail' i.id %}" class="btn btn-danger">Show more</a>
                 </div>
           </div>
        </div>
        {% endfor %}
    </div>
</div>
<style>

    .card:hover{
transform: scale(1.05);
box-shadow: 0 0 10px red;

}
</style>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
<div class="container-fluid mt-4">
    <h3 class="text-center">You Have Searched for <span class="text light">{{q}}</span> </h3>
</div>
</center>

<div class="container" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3">
            <div class="card mt-5" style="width: 18rem;">
            <a href="{% url 'shop:prodetail' i.id %}"><img src="{{ i.image.url }}" width="100%" height="200px" class="card-img-top" alt="..."></a>
                 <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                     <h5 class="card-title">${{i.price}}</h5>
                     <p class="card-text" style="text-align:justify;"></p>
                 </div>
           </div>
        </div>
        {% empty %}
        <h3 class="text-center text-danger">No result found</h3>
        {% endfor %}
    </div>
</div>


{% endblock %}